/*
 * Copyright (C) 2008-2010 Freescale Semiconductor, Inc. All Rights Reserved.
 */

/*
 * The code contained herein is licensed under the GNU General Public
 * License. You may obtain a copy of the GNU General Public License
 * Version 2 or later at the following locations:
 *
 * http://www.opensource.org/licenses/gpl-license.html
 * http://www.gnu.org/copyleft/gpl.html
 */

#include <linux/errno.h>
#include <linux/module.h>
#include <linux/platform_device.h>
#include <linux/delay.h>
#include <asm/io.h>
#include <mach/hardware.h>
#include <mach/clock.h>
#include <mach/gpio.h>

#include "iomux.h"
#include "mx51_pins.h"

/*!
 * @file mach-mx5/mx51_3stack_gpio.c
 *
 * @brief This file contains all the GPIO setup functions for the board.
 *
 * @ingroup GPIO
 */
static struct mxc_iomux_pin_cfg __initdata mxc_iomux_pins[] = {
	/* CSI1 - ADP-DISP board, OV2655 cam */
	{       /* pwdn */
		MX51_PIN_CSI1_D8, IOMUX_CONFIG_ALT3, 
		PAD_CTL_PKE_ENABLE, 
		MUX_IN_GPIO3_IPP_IND_G_IN_12_SELECT_INPUT, 
		INPUT_CTL_PATH1, 
	}, 
	{       /* reset */
		MX51_PIN_DISPB2_SER_DIO, IOMUX_CONFIG_GPIO,
	},
	{       /* data */
		MX51_PIN_CSI1_D10, IOMUX_CONFIG_ALT0, PAD_CTL_HYS_NONE,
	},
        {
		MX51_PIN_CSI1_D11, IOMUX_CONFIG_ALT0, PAD_CTL_HYS_NONE,
        },
        {
		MX51_PIN_CSI1_D12, IOMUX_CONFIG_ALT0, PAD_CTL_HYS_NONE,
        },
        {
		MX51_PIN_CSI1_D13, IOMUX_CONFIG_ALT0, PAD_CTL_HYS_NONE,
        },
        {
		MX51_PIN_CSI1_D14, IOMUX_CONFIG_ALT0, PAD_CTL_HYS_NONE,
        },
        {
		MX51_PIN_CSI1_D15, IOMUX_CONFIG_ALT0, PAD_CTL_HYS_NONE,
        },
        {
		MX51_PIN_CSI1_D16, IOMUX_CONFIG_ALT0, PAD_CTL_HYS_NONE,
	},
	{
		MX51_PIN_CSI1_D17, IOMUX_CONFIG_ALT0, PAD_CTL_HYS_NONE,
        },
	{
		MX51_PIN_CSI1_D18, IOMUX_CONFIG_ALT0, PAD_CTL_HYS_NONE,
	},
	{
		MX51_PIN_CSI1_D19, IOMUX_CONFIG_ALT0, PAD_CTL_HYS_NONE,
	},
	{       /* sync */
		MX51_PIN_CSI1_VSYNC, IOMUX_CONFIG_ALT0,
		(PAD_CTL_HYS_NONE | PAD_CTL_SRE_SLOW),
	},
	{
		MX51_PIN_CSI1_HSYNC, IOMUX_CONFIG_ALT0,
		(PAD_CTL_HYS_NONE | PAD_CTL_SRE_SLOW),
	},
	/* CSI1_PIXCLK no muxing */
	/* CSI1_MCLK no muxing */
#if 0	
	/* 1-wire */
	{
		MX51_PIN_OWIRE_LINE, IOMUX_CONFIG_ALT0,
		(PAD_CTL_HYS_ENABLE | PAD_CTL_PKE_ENABLE |
		 PAD_CTL_ODE_OPENDRAIN_ENABLE | PAD_CTL_DRV_HIGH |
		 PAD_CTL_SRE_FAST),
	},
#endif
	/* Keypad */
	{
		MX51_PIN_KEY_COL0, IOMUX_CONFIG_ALT0,
	},
	{
		MX51_PIN_KEY_COL1, IOMUX_CONFIG_ALT0,
	},
	{
		MX51_PIN_KEY_COL2, IOMUX_CONFIG_ALT0,
	},
	{
		MX51_PIN_KEY_COL3, IOMUX_CONFIG_ALT0,
	},
	{
		MX51_PIN_KEY_COL4, IOMUX_CONFIG_ALT0,
	},
	{
		MX51_PIN_KEY_COL5, IOMUX_CONFIG_ALT0,
	},
	{
		MX51_PIN_KEY_ROW0, IOMUX_CONFIG_ALT0,
	},
	{
		MX51_PIN_KEY_ROW1, IOMUX_CONFIG_ALT0,
	},
	{
		MX51_PIN_KEY_ROW2, IOMUX_CONFIG_ALT0,
	},
	{
		MX51_PIN_KEY_ROW3, IOMUX_CONFIG_ALT0,
	},
	/* AUD 3 */
	{
		MX51_PIN_AUD3_BB_TXD, IOMUX_CONFIG_ALT0,
		(PAD_CTL_SRE_FAST | PAD_CTL_DRV_HIGH |
		 PAD_CTL_ODE_OPENDRAIN_NONE | PAD_CTL_100K_PU |
		 PAD_CTL_HYS_NONE | PAD_CTL_DDR_INPUT_CMOS | PAD_CTL_DRV_VOT_LOW),
	},
	{
		MX51_PIN_AUD3_BB_RXD, IOMUX_CONFIG_ALT0,
		(PAD_CTL_SRE_FAST | PAD_CTL_DRV_HIGH |
		 PAD_CTL_ODE_OPENDRAIN_NONE | PAD_CTL_100K_PU |
		 PAD_CTL_HYS_NONE | PAD_CTL_DDR_INPUT_CMOS | PAD_CTL_DRV_VOT_LOW),
	},
	{
		MX51_PIN_AUD3_BB_CK, IOMUX_CONFIG_ALT0,
		(PAD_CTL_SRE_FAST | PAD_CTL_DRV_HIGH |
		 PAD_CTL_ODE_OPENDRAIN_NONE | PAD_CTL_100K_PU |
		 PAD_CTL_HYS_NONE | PAD_CTL_DDR_INPUT_CMOS | PAD_CTL_DRV_VOT_LOW),
	},
	{
		MX51_PIN_AUD3_BB_FS, IOMUX_CONFIG_ALT0,
		(PAD_CTL_SRE_FAST | PAD_CTL_DRV_HIGH |
		 PAD_CTL_ODE_OPENDRAIN_NONE | PAD_CTL_100K_PU |
		 PAD_CTL_HYS_NONE | PAD_CTL_DDR_INPUT_CMOS | PAD_CTL_DRV_VOT_LOW),
	},
	/* Audio AMP enable */
	{
		MX51_PIN_EIM_A27, IOMUX_CONFIG_GPIO,
	},
	/* DI2 */
	{	/* DE */
		MX51_PIN_DI_GP4, IOMUX_CONFIG_ALT4,
	},
	{	/* clk */
		MX51_PIN_DI2_DISP_CLK, IOMUX_CONFIG_ALT0,
		(PAD_CTL_SRE_FAST | PAD_CTL_DRV_MAX),
	},
#if 0
	{
		MX51_PIN_DISP1_DAT0, IOMUX_CONFIG_ALT0,
		(PAD_CTL_HYS_NONE | PAD_CTL_DRV_LOW | PAD_CTL_SRE_FAST),
	},
	{
		MX51_PIN_DISP1_DAT1, IOMUX_CONFIG_ALT0,
		(PAD_CTL_HYS_NONE | PAD_CTL_DRV_LOW | PAD_CTL_SRE_FAST),
	},
	{
		MX51_PIN_DISP1_DAT2, IOMUX_CONFIG_ALT0,
		(PAD_CTL_HYS_NONE | PAD_CTL_DRV_LOW | PAD_CTL_SRE_FAST),
	},
	{
		MX51_PIN_DISP1_DAT3, IOMUX_CONFIG_ALT0,
		(PAD_CTL_HYS_NONE | PAD_CTL_DRV_LOW | PAD_CTL_SRE_FAST),
	},
	{
		MX51_PIN_DISP1_DAT4, IOMUX_CONFIG_ALT0,
		(PAD_CTL_HYS_NONE | PAD_CTL_DRV_LOW | PAD_CTL_SRE_FAST),
	},
	{
		MX51_PIN_DISP1_DAT5, IOMUX_CONFIG_ALT0,
		(PAD_CTL_HYS_NONE | PAD_CTL_DRV_LOW | PAD_CTL_SRE_FAST),
	},
	{
		MX51_PIN_DISP1_DAT6, IOMUX_CONFIG_ALT0,
		(PAD_CTL_HYS_NONE | PAD_CTL_DRV_LOW | PAD_CTL_SRE_FAST),
	},
	{
		MX51_PIN_DISP1_DAT7, IOMUX_CONFIG_ALT0,
		(PAD_CTL_HYS_NONE | PAD_CTL_DRV_LOW | PAD_CTL_SRE_FAST),
	},
	{
		MX51_PIN_DISP1_DAT8, IOMUX_CONFIG_ALT0,
		(PAD_CTL_HYS_NONE | PAD_CTL_DRV_LOW | PAD_CTL_SRE_FAST),
	},
	{
		MX51_PIN_DISP1_DAT9, IOMUX_CONFIG_ALT0,
		(PAD_CTL_HYS_NONE | PAD_CTL_DRV_LOW | PAD_CTL_SRE_FAST),
	},
	{
		MX51_PIN_DISP1_DAT10, IOMUX_CONFIG_ALT0,
		(PAD_CTL_HYS_NONE | PAD_CTL_DRV_LOW | PAD_CTL_SRE_FAST),
	},
	{
		MX51_PIN_DISP1_DAT11, IOMUX_CONFIG_ALT0,
		(PAD_CTL_HYS_NONE | PAD_CTL_DRV_LOW | PAD_CTL_SRE_FAST),
	},
	{
		MX51_PIN_DISP1_DAT12, IOMUX_CONFIG_ALT0,
		(PAD_CTL_HYS_NONE | PAD_CTL_DRV_LOW | PAD_CTL_SRE_FAST),
	},
	{
		MX51_PIN_DISP1_DAT13, IOMUX_CONFIG_ALT0,
		(PAD_CTL_HYS_NONE | PAD_CTL_DRV_LOW | PAD_CTL_SRE_FAST),
	},
	{
		MX51_PIN_DISP1_DAT14, IOMUX_CONFIG_ALT0,
		(PAD_CTL_HYS_NONE | PAD_CTL_DRV_LOW | PAD_CTL_SRE_FAST),
	},
	{
		MX51_PIN_DISP1_DAT15, IOMUX_CONFIG_ALT0,
		(PAD_CTL_HYS_NONE | PAD_CTL_DRV_LOW | PAD_CTL_SRE_FAST),
	},
	{
		MX51_PIN_DISP1_DAT16, IOMUX_CONFIG_ALT0,
		(PAD_CTL_HYS_NONE | PAD_CTL_DRV_LOW | PAD_CTL_SRE_FAST),
	},
	{
		MX51_PIN_DISP1_DAT17, IOMUX_CONFIG_ALT0,
		(PAD_CTL_HYS_NONE | PAD_CTL_DRV_LOW | PAD_CTL_SRE_FAST),
	},
	{
		MX51_PIN_DISP1_DAT18, IOMUX_CONFIG_ALT0,
		(PAD_CTL_HYS_NONE | PAD_CTL_DRV_LOW | PAD_CTL_SRE_FAST),
	},
	{
		MX51_PIN_DISP1_DAT19, IOMUX_CONFIG_ALT0,
		(PAD_CTL_HYS_NONE | PAD_CTL_DRV_LOW | PAD_CTL_SRE_FAST),
	},
	{
		MX51_PIN_DISP1_DAT20, IOMUX_CONFIG_ALT0,
		(PAD_CTL_HYS_NONE | PAD_CTL_DRV_LOW | PAD_CTL_SRE_FAST),
	},
	{
		MX51_PIN_DISP1_DAT21, IOMUX_CONFIG_ALT0,
		(PAD_CTL_HYS_NONE | PAD_CTL_DRV_LOW | PAD_CTL_SRE_FAST),
	},
	{
		MX51_PIN_DISP1_DAT22, IOMUX_CONFIG_ALT0,
		(PAD_CTL_HYS_NONE | PAD_CTL_DRV_LOW | PAD_CTL_SRE_FAST),
	},
	{
		MX51_PIN_DISP1_DAT23, IOMUX_CONFIG_ALT0,
		(PAD_CTL_HYS_NONE | PAD_CTL_DRV_LOW | PAD_CTL_SRE_FAST),
	},
#endif
	{	/* ad9889 irq */
		MX51_PIN_DI1_D1_CS,
		(IOMUX_CONFIG_ALT4 | IOMUX_CONFIG_SION),
		0x85, /* default */
		MUX_IN_GPIO3_IPP_IND_G_IN_4_SELECT_INPUT,
		INPUT_CTL_PATH1,
	},
	/* SPDIF */
	{
		MX51_PIN_GPIO1_7, IOMUX_CONFIG_ALT2,
		(PAD_CTL_DRV_HIGH | PAD_CTL_PUE_PULL |
		 PAD_CTL_100K_PU | PAD_CTL_PKE_ENABLE |
		 PAD_CTL_SRE_FAST),
	},
	/* USBH1 */
	{
		MX51_PIN_USBH1_STP, IOMUX_CONFIG_ALT0,
		(PAD_CTL_SRE_FAST | PAD_CTL_DRV_HIGH | PAD_CTL_PUE_KEEPER |
		 PAD_CTL_PKE_ENABLE | PAD_CTL_HYS_ENABLE),
	},
	{			/* USBH1_CLK */
		MX51_PIN_USBH1_CLK, IOMUX_CONFIG_ALT0,
		(PAD_CTL_SRE_FAST | PAD_CTL_DRV_HIGH | PAD_CTL_PUE_KEEPER |
		 PAD_CTL_PKE_ENABLE | PAD_CTL_HYS_ENABLE | PAD_CTL_DDR_INPUT_CMOS),
	},
	{			/* USBH1_DIR */
		MX51_PIN_USBH1_DIR, IOMUX_CONFIG_ALT0,
		(PAD_CTL_SRE_FAST | PAD_CTL_DRV_HIGH | PAD_CTL_PUE_KEEPER |
		 PAD_CTL_PKE_ENABLE | PAD_CTL_HYS_ENABLE | PAD_CTL_DDR_INPUT_CMOS),
	},
	{			/* USBH1_NXT */
		MX51_PIN_USBH1_NXT, IOMUX_CONFIG_ALT0,
		(PAD_CTL_SRE_FAST | PAD_CTL_DRV_HIGH | PAD_CTL_PUE_KEEPER |
		 PAD_CTL_PKE_ENABLE | PAD_CTL_HYS_ENABLE | PAD_CTL_DDR_INPUT_CMOS),
	},
	{			/* USBH1_DATA0 */
		MX51_PIN_USBH1_DATA0, IOMUX_CONFIG_ALT0,
		(PAD_CTL_SRE_FAST | PAD_CTL_DRV_HIGH | PAD_CTL_100K_PU |
		 PAD_CTL_PUE_KEEPER | PAD_CTL_PKE_ENABLE | PAD_CTL_HYS_ENABLE),
	},
	{			/* USBH1_DATA1 */
		MX51_PIN_USBH1_DATA1, IOMUX_CONFIG_ALT0,
		(PAD_CTL_SRE_FAST | PAD_CTL_DRV_HIGH | PAD_CTL_100K_PU |
		 PAD_CTL_PUE_KEEPER | PAD_CTL_PKE_ENABLE | PAD_CTL_HYS_ENABLE),
	},
	{			/* USBH1_DATA2 */
		MX51_PIN_USBH1_DATA2, IOMUX_CONFIG_ALT0,
		(PAD_CTL_SRE_FAST | PAD_CTL_DRV_HIGH | PAD_CTL_100K_PU |
		 PAD_CTL_PUE_KEEPER | PAD_CTL_PKE_ENABLE | PAD_CTL_HYS_ENABLE),
	},
	{			/* USBH1_DATA3 */
		MX51_PIN_USBH1_DATA3, IOMUX_CONFIG_ALT0,
		(PAD_CTL_SRE_FAST | PAD_CTL_DRV_HIGH | PAD_CTL_100K_PU |
		 PAD_CTL_PUE_KEEPER | PAD_CTL_PKE_ENABLE | PAD_CTL_HYS_ENABLE),
	},
	{			/* USBH1_DATA4 */
		MX51_PIN_USBH1_DATA4, IOMUX_CONFIG_ALT0,
		(PAD_CTL_SRE_FAST | PAD_CTL_DRV_HIGH | PAD_CTL_100K_PU |
		 PAD_CTL_PUE_KEEPER | PAD_CTL_PKE_ENABLE | PAD_CTL_HYS_ENABLE),
	},
	{			/* USBH1_DATA5 */
		MX51_PIN_USBH1_DATA5, IOMUX_CONFIG_ALT0,
		(PAD_CTL_SRE_FAST | PAD_CTL_DRV_HIGH | PAD_CTL_100K_PU |
		 PAD_CTL_PUE_KEEPER | PAD_CTL_PKE_ENABLE | PAD_CTL_HYS_ENABLE),
	},
	{			/* USBH1_DATA6 */
		MX51_PIN_USBH1_DATA6, IOMUX_CONFIG_ALT0,
		(PAD_CTL_SRE_FAST | PAD_CTL_DRV_HIGH | PAD_CTL_100K_PU |
		 PAD_CTL_PUE_KEEPER | PAD_CTL_PKE_ENABLE | PAD_CTL_HYS_ENABLE),
	},
	{			/* USBH1_DATA7 */
		MX51_PIN_USBH1_DATA7, IOMUX_CONFIG_ALT0,
		(PAD_CTL_SRE_FAST | PAD_CTL_DRV_HIGH | PAD_CTL_100K_PU |
		 PAD_CTL_PUE_KEEPER | PAD_CTL_PKE_ENABLE | PAD_CTL_HYS_ENABLE),
	},
	{	/* PHY reset */
		MX51_PIN_CSI2_HSYNC, IOMUX_CONFIG_ALT3,
		(PAD_CTL_DRV_HIGH | PAD_CTL_HYS_NONE | PAD_CTL_PUE_KEEPER |
		 PAD_CTL_100K_PU | PAD_CTL_ODE_OPENDRAIN_NONE | PAD_CTL_PKE_ENABLE | 
		 PAD_CTL_SRE_FAST),
	},
	/* SD1 */
	{
		MX51_PIN_SD1_CMD, IOMUX_CONFIG_ALT0 | IOMUX_CONFIG_SION,
		(PAD_CTL_DRV_MAX | PAD_CTL_22K_PU | PAD_CTL_SRE_FAST),
	},
	{
		MX51_PIN_SD1_CLK, IOMUX_CONFIG_ALT0 | IOMUX_CONFIG_SION,
		(PAD_CTL_DRV_MAX | PAD_CTL_22K_PU | PAD_CTL_SRE_FAST),
	},
	{
		MX51_PIN_SD1_DATA0, IOMUX_CONFIG_ALT0,
		(PAD_CTL_DRV_MAX | PAD_CTL_22K_PU | PAD_CTL_SRE_FAST),
	},
	{
		MX51_PIN_SD1_DATA1, IOMUX_CONFIG_ALT0,
		(PAD_CTL_DRV_MAX | PAD_CTL_22K_PU | PAD_CTL_SRE_FAST),
	},
	{
		MX51_PIN_SD1_DATA2, IOMUX_CONFIG_ALT0,
		(PAD_CTL_DRV_MAX | PAD_CTL_22K_PU | PAD_CTL_SRE_FAST),
	},
	{
		MX51_PIN_SD1_DATA3, IOMUX_CONFIG_ALT0,
		(PAD_CTL_DRV_MAX | PAD_CTL_22K_PU | PAD_CTL_SRE_FAST),
	},
	{
		MX51_PIN_GPIO1_0, IOMUX_CONFIG_GPIO | IOMUX_CONFIG_SION,
		(PAD_CTL_HYS_ENABLE | PAD_CTL_100K_PU),
	},
	{
		MX51_PIN_GPIO1_1, IOMUX_CONFIG_GPIO | IOMUX_CONFIG_SION,
		(PAD_CTL_HYS_ENABLE | PAD_CTL_100K_PU),
	},
#if 0
	/* SD 2 */
	{
		MX51_PIN_SD2_CMD, IOMUX_CONFIG_ALT0 | IOMUX_CONFIG_SION,
		(PAD_CTL_DRV_MAX | PAD_CTL_22K_PU | PAD_CTL_SRE_FAST),
	},
	{
		MX51_PIN_SD2_CLK, IOMUX_CONFIG_ALT0 | IOMUX_CONFIG_SION,
		(PAD_CTL_DRV_MAX | PAD_CTL_22K_PU | PAD_CTL_SRE_FAST),
	},
	{
		MX51_PIN_SD2_DATA0, IOMUX_CONFIG_ALT0,
		(PAD_CTL_DRV_MAX | PAD_CTL_22K_PU | PAD_CTL_SRE_FAST),
	},
	{
		MX51_PIN_SD2_DATA1, IOMUX_CONFIG_ALT0,
		(PAD_CTL_DRV_MAX | PAD_CTL_22K_PU | PAD_CTL_SRE_FAST),
	},
	{
		MX51_PIN_SD2_DATA2, IOMUX_CONFIG_ALT0,
		(PAD_CTL_DRV_MAX | PAD_CTL_22K_PU | PAD_CTL_SRE_FAST),
	},
	{
		MX51_PIN_SD2_DATA3, IOMUX_CONFIG_ALT0,
		(PAD_CTL_DRV_MAX | PAD_CTL_22K_PU | PAD_CTL_SRE_FAST),
	},
#endif
	/* UART 1 */
	{
		MX51_PIN_UART1_RXD, IOMUX_CONFIG_ALT0,
		(PAD_CTL_HYS_ENABLE | PAD_CTL_PKE_ENABLE | PAD_CTL_PUE_PULL |
		 PAD_CTL_DRV_HIGH | PAD_CTL_SRE_FAST),
		MUX_IN_UART1_IPP_UART_RXD_MUX_SELECT_INPUT,
		INPUT_CTL_PATH0,
	},
	{
		MX51_PIN_UART1_TXD, IOMUX_CONFIG_ALT0,
		(PAD_CTL_HYS_ENABLE | PAD_CTL_PKE_ENABLE | PAD_CTL_PUE_PULL |
		 PAD_CTL_DRV_HIGH | PAD_CTL_SRE_FAST),
	},
	{
		MX51_PIN_UART1_RTS, IOMUX_CONFIG_ALT0,
		(PAD_CTL_HYS_ENABLE | PAD_CTL_PKE_ENABLE | PAD_CTL_PUE_PULL |
		 PAD_CTL_DRV_HIGH),
		MUX_IN_UART1_IPP_UART_RTS_B_SELECT_INPUT,
		INPUT_CTL_PATH0,
	},
	{
		MX51_PIN_UART1_CTS, IOMUX_CONFIG_ALT0,
		(PAD_CTL_HYS_ENABLE | PAD_CTL_PKE_ENABLE | PAD_CTL_PUE_PULL |
		 PAD_CTL_DRV_HIGH),
	},
	/* UART 2 */
	{
		MX51_PIN_UART2_RXD, IOMUX_CONFIG_ALT0,
		(PAD_CTL_HYS_NONE | PAD_CTL_PKE_ENABLE | PAD_CTL_PUE_PULL |
		 PAD_CTL_DRV_HIGH | PAD_CTL_SRE_FAST),
		MUX_IN_UART2_IPP_UART_RXD_MUX_SELECT_INPUT,
		INPUT_CTL_PATH2,
	},
	{
		MX51_PIN_UART2_TXD, IOMUX_CONFIG_ALT0,
		(PAD_CTL_HYS_NONE | PAD_CTL_PKE_ENABLE | PAD_CTL_PUE_PULL |
		 PAD_CTL_DRV_HIGH | PAD_CTL_SRE_FAST),
	},
	/* UART 3 */
	{
		MX51_PIN_UART3_RXD, IOMUX_CONFIG_ALT1,
		(PAD_CTL_HYS_NONE | PAD_CTL_PKE_ENABLE | PAD_CTL_PUE_PULL |
		 PAD_CTL_DRV_HIGH | PAD_CTL_SRE_FAST),
		MUX_IN_UART3_IPP_UART_RXD_MUX_SELECT_INPUT,
		INPUT_CTL_PATH4,
	},
	{
		MX51_PIN_UART3_TXD, IOMUX_CONFIG_ALT1,
		(PAD_CTL_HYS_NONE | PAD_CTL_PKE_ENABLE | PAD_CTL_PUE_PULL |
		 PAD_CTL_DRV_HIGH | PAD_CTL_SRE_FAST),
	},
	/* Ethernet PHY */
	{			/* COL */
		MX51_PIN_NANDF_RB2, IOMUX_CONFIG_ALT1,
		(PAD_CTL_HYS_ENABLE | PAD_CTL_PKE_ENABLE),
	},
	{			/* RX_CLK */
		MX51_PIN_NANDF_RB3, IOMUX_CONFIG_ALT1,
		(PAD_CTL_HYS_ENABLE | PAD_CTL_PKE_ENABLE),
	},
	{			/* MDC */
		MX51_PIN_NANDF_CS3, IOMUX_CONFIG_ALT2,
		(PAD_CTL_DRV_VOT_HIGH | PAD_CTL_DRV_HIGH),
	},
	{			/* TDATA[1] */
		MX51_PIN_NANDF_CS4, IOMUX_CONFIG_ALT2,
		(PAD_CTL_DRV_VOT_HIGH | PAD_CTL_DRV_HIGH),
	},
	{			/* TDATA[2] */
		MX51_PIN_NANDF_CS5, IOMUX_CONFIG_ALT2,
		(PAD_CTL_DRV_VOT_HIGH | PAD_CTL_DRV_HIGH),
	},
	{			/* TDATA[3] */
		MX51_PIN_NANDF_CS6, IOMUX_CONFIG_ALT2,
		(PAD_CTL_DRV_VOT_HIGH | PAD_CTL_DRV_HIGH),
	},
	{			/* TX_EN */
		MX51_PIN_NANDF_CS7, IOMUX_CONFIG_ALT1,
		(PAD_CTL_DRV_VOT_HIGH | PAD_CTL_DRV_HIGH),
	},
	{			/* TX_CLK */
		MX51_PIN_NANDF_RDY_INT, IOMUX_CONFIG_ALT1,
		(PAD_CTL_DRV_VOT_HIGH | PAD_CTL_HYS_ENABLE | PAD_CTL_PKE_ENABLE),
	},
	{			/* RX DV */
		MX51_PIN_NANDF_D11, IOMUX_CONFIG_ALT2,
		(PAD_CTL_DRV_VOT_HIGH | PAD_CTL_DRV_HIGH),
	},
	{			/* RDATA[0] */
		MX51_PIN_NANDF_D9, IOMUX_CONFIG_ALT2,
		(PAD_CTL_HYS_ENABLE | PAD_CTL_PKE_ENABLE),
	},
	{			/* TDATA[0] */
		MX51_PIN_NANDF_D8, IOMUX_CONFIG_ALT2,
		(PAD_CTL_DRV_VOT_HIGH | PAD_CTL_DRV_HIGH),
	},
	{			/* MDIO */
		MX51_PIN_EIM_EB2, IOMUX_CONFIG_ALT3,
		(PAD_CTL_SRE_FAST | PAD_CTL_DRV_HIGH | PAD_CTL_ODE_OPENDRAIN_ENABLE |
		 PAD_CTL_22K_PU | PAD_CTL_HYS_ENABLE | PAD_CTL_PKE_ENABLE |
		 PAD_CTL_PUE_PULL),
	},
	{			/* RDATA[1] */
		MX51_PIN_EIM_EB3, IOMUX_CONFIG_ALT3,
		(PAD_CTL_HYS_ENABLE | PAD_CTL_PKE_ENABLE),
	},
	{			/* RDATA[2] */
		MX51_PIN_EIM_CS2, IOMUX_CONFIG_ALT3,
		(PAD_CTL_HYS_ENABLE | PAD_CTL_PKE_ENABLE),
	},
	{			/* RDATA[3] */
		MX51_PIN_EIM_CS3, IOMUX_CONFIG_ALT3,
		(PAD_CTL_HYS_ENABLE | PAD_CTL_PKE_ENABLE),
	},
	{			/* RX_ER */
		MX51_PIN_EIM_CS4, IOMUX_CONFIG_ALT3,
		(PAD_CTL_HYS_ENABLE | PAD_CTL_PKE_ENABLE),
	},
	{			/* CRS */
		MX51_PIN_EIM_CS5, IOMUX_CONFIG_ALT3,
		(PAD_CTL_HYS_ENABLE | PAD_CTL_PKE_ENABLE),
	},
	{			/* TX ER as IRQ */
		MX51_PIN_NANDF_CS2, IOMUX_CONFIG_GPIO | IOMUX_CONFIG_SION,
		(PAD_CTL_HYS_ENABLE | PAD_CTL_100K_PU),
	},
	/* I2C1 */
	{
		MX51_PIN_CSPI1_SCLK,
		IOMUX_CONFIG_ALT1 | IOMUX_CONFIG_SION,
		(PAD_CTL_SRE_FAST | PAD_CTL_ODE_OPENDRAIN_ENABLE |
		 PAD_CTL_DRV_HIGH | PAD_CTL_100K_PU |
		 PAD_CTL_HYS_ENABLE),
		MUX_IN_I2C1_IPP_SCL_IN_SELECT_INPUT, INPUT_CTL_PATH1,
	},
	{
		MX51_PIN_CSPI1_MOSI,
		IOMUX_CONFIG_ALT1 | IOMUX_CONFIG_SION,
		(PAD_CTL_SRE_FAST | PAD_CTL_ODE_OPENDRAIN_ENABLE |
		 PAD_CTL_DRV_HIGH | PAD_CTL_100K_PU |
		 PAD_CTL_HYS_ENABLE),
		MUX_IN_I2C1_IPP_SDA_IN_SELECT_INPUT, INPUT_CTL_PATH1,
	},
	/* I2C2 */
	{
		MX51_PIN_EIM_D24,
		IOMUX_CONFIG_ALT4 | IOMUX_CONFIG_SION,
		(PAD_CTL_SRE_FAST | PAD_CTL_ODE_OPENDRAIN_ENABLE |
		 PAD_CTL_DRV_HIGH | PAD_CTL_100K_PU |
		 PAD_CTL_HYS_ENABLE),
		MUX_IN_I2C2_IPP_SCL_IN_SELECT_INPUT, INPUT_CTL_PATH0,
	},
	{
		MX51_PIN_EIM_D27,
		IOMUX_CONFIG_ALT4 | IOMUX_CONFIG_SION,
		(PAD_CTL_SRE_FAST | PAD_CTL_ODE_OPENDRAIN_ENABLE |
		 PAD_CTL_DRV_HIGH | PAD_CTL_100K_PU |
		 PAD_CTL_HYS_ENABLE),
		MUX_IN_I2C2_IPP_SDA_IN_SELECT_INPUT, INPUT_CTL_PATH0,
	},
	/* NAND flash */
	{
		MX51_PIN_NANDF_CS0, IOMUX_CONFIG_ALT0,
	},
	{
		MX51_PIN_NANDF_CS1, IOMUX_CONFIG_ALT0,
	},
	{
		MX51_PIN_NANDF_RB0, IOMUX_CONFIG_ALT0,
	},
	{
		MX51_PIN_NANDF_RB1, IOMUX_CONFIG_ALT0,
	},
	{
		MX51_PIN_NANDF_D0, IOMUX_CONFIG_ALT0,
	},
	{
		MX51_PIN_NANDF_D1, IOMUX_CONFIG_ALT0,
	},
	{
		MX51_PIN_NANDF_D2, IOMUX_CONFIG_ALT0,
	},
	{
		MX51_PIN_NANDF_D3, IOMUX_CONFIG_ALT0,
	},
	{
		MX51_PIN_NANDF_D4, IOMUX_CONFIG_ALT0,
	},
	{
		MX51_PIN_NANDF_D5, IOMUX_CONFIG_ALT0,
	},
	{
		MX51_PIN_NANDF_D6, IOMUX_CONFIG_ALT0,
	},
	{
		MX51_PIN_NANDF_D7, IOMUX_CONFIG_ALT0,
	},
	{
		MX51_PIN_NANDF_RE_B, IOMUX_CONFIG_ALT0,
	},
	{
		MX51_PIN_NANDF_WE_B, IOMUX_CONFIG_ALT0,
	},
	{
		MX51_PIN_NANDF_WP_B, IOMUX_CONFIG_ALT0,
	},
	{
		MX51_PIN_NANDF_ALE, IOMUX_CONFIG_ALT0,
	},
	{
		MX51_PIN_NANDF_CLE, IOMUX_CONFIG_ALT0,
	},
	/* Backlight PWM */
	{
		MX51_PIN_GPIO1_2, IOMUX_CONFIG_ALT1,
	},
	/* Emerging display */
	{	/* reset */
		MX51_PIN_DISPB2_SER_RS, IOMUX_CONFIG_GPIO,
	},
	/* Toshiba display */
	{	/* on/off */
		MX51_PIN_DISPB2_SER_CLK, IOMUX_CONFIG_GPIO,
	},
	/* Bluetooth module */
	{	/* reset */
		MX51_PIN_GPIO1_9, IOMUX_CONFIG_GPIO,
	},
	{	/* onoff */
		MX51_PIN_GPIO1_8, IOMUX_CONFIG_GPIO,
	},
	{	/* sleepx */
		MX51_PIN_GPIO1_6, IOMUX_CONFIG_GPIO,
	},
	/* GSM/GPRS module */
	{	/* pwr_on */
		MX51_PIN_EIM_D22, IOMUX_CONFIG_GPIO,
		0x5,
	},
	{	/* reset_n */
		MX51_PIN_EIM_D23, IOMUX_CONFIG_GPIO,
		0x5,
	},
	{
		MX51_PIN_EIM_D19, IOMUX_CONFIG_GPIO,
		0x5,
	},
	{
		MX51_PIN_EIM_D16, IOMUX_CONFIG_GPIO,
		0x5,
	},
	{
		MX51_PIN_EIM_D21, IOMUX_CONFIG_GPIO,
		0x5,
	},
	{
		MX51_PIN_EIM_D20, IOMUX_CONFIG_GPIO,
		0x5,
	},
	/* GPS module */
	{
		MX51_PIN_GPIO1_3, IOMUX_CONFIG_GPIO,
	},
	{
		MX51_PIN_OWIRE_LINE, IOMUX_CONFIG_GPIO,
		0x8,
	},


	/* IO extender board */
	{//outputs:
		MX51_PIN_CSPI1_MISO, IOMUX_CONFIG_ALT3, // -> GPIO 4_23
	},
	{
		MX51_PIN_CSPI1_SS0, IOMUX_CONFIG_ALT3, 	// -> GPIO 4_24
	},
	{
		MX51_PIN_CSPI1_SS1, IOMUX_CONFIG_ALT3, 	// -> GPIO 4_25
	},
	{
		MX51_PIN_CSPI1_RDY, IOMUX_CONFIG_ALT3, 	// -> GPIO 4_26
	},
	{//inputs:
		MX51_PIN_EIM_D20, IOMUX_CONFIG_ALT1, // -> GPIO 2_4
	},
	{
		MX51_PIN_EIM_D21, IOMUX_CONFIG_ALT1, 	// -> GPIO 2_5 
	},
	{
		MX51_PIN_EIM_D22, IOMUX_CONFIG_ALT1, 	// -> GPIO 2_6
	},
	{
		MX51_PIN_EIM_D23, IOMUX_CONFIG_ALT1, 	// -> GPIO 2_7
	},

};

static int __initdata enable_ata = { 0 };
static int __init ata_setup(char *__unused)
{
	enable_ata = 1;
	return 1;
}

__setup("ata", ata_setup);

static int __initdata enable_sim = { 0 };
static int __init sim_setup(char *__unused)
{
	enable_sim = 1;
	return 1;
}

__setup("sim", sim_setup);

void __init mx51_3stack_io_init(void)
{
	int i, num;
	struct mxc_iomux_pin_cfg *pin_ptr;

	for (i = 0; i < ARRAY_SIZE(mxc_iomux_pins); i++) {
		mxc_request_iomux(mxc_iomux_pins[i].pin,
				  mxc_iomux_pins[i].mux_mode);
		if (mxc_iomux_pins[i].pad_cfg)
			mxc_iomux_set_pad(mxc_iomux_pins[i].pin,
					  mxc_iomux_pins[i].pad_cfg);
		if (mxc_iomux_pins[i].in_select)
			mxc_iomux_set_input(mxc_iomux_pins[i].in_select,
					  mxc_iomux_pins[i].in_mode);
	}

	/* TO3 doesn't need pad to drive CSI_DATA_EN[0] high */
	if (cpu_is_mx51_rev(CHIP_REV_3_0) > 0)
		mxc_request_iomux(MX51_PIN_EIM_A26, IOMUX_CONFIG_ALT0);


	/* Ethernet PHY INT */
	gpio_request(IOMUX_TO_GPIO(MX51_PIN_NANDF_CS2), "nandf_cs2");
	gpio_direction_input(IOMUX_TO_GPIO(MX51_PIN_NANDF_CS2));

	/* De-assert USB PHY RESETB */
	gpio_request(IOMUX_TO_GPIO(MX51_PIN_CSI2_HSYNC), "usb phy reset");
	gpio_direction_output(IOMUX_TO_GPIO(MX51_PIN_CSI2_HSYNC), 1);

	/* ad9889 irq */
	gpio_request(IOMUX_TO_GPIO(MX51_PIN_DI1_D1_CS), "di1_d1_cs");
	gpio_direction_input(IOMUX_TO_GPIO(MX51_PIN_DI1_D1_CS));

	/* SD 1 */
	gpio_request(IOMUX_TO_GPIO(MX51_PIN_GPIO1_0), "gpio1_0");
	gpio_direction_input(IOMUX_TO_GPIO(MX51_PIN_GPIO1_0));	/* SD1 CD */
	gpio_request(IOMUX_TO_GPIO(MX51_PIN_GPIO1_1), "gpio1_1");
	gpio_direction_input(IOMUX_TO_GPIO(MX51_PIN_GPIO1_1));	/* SD1 WP */

	/* Display resets */
	gpio_request(IOMUX_TO_GPIO(MX51_PIN_DISPB2_SER_RS), "dispb2_ser_rs");
	gpio_direction_output(IOMUX_TO_GPIO(MX51_PIN_DISPB2_SER_RS), 1);
	gpio_request(IOMUX_TO_GPIO(MX51_PIN_DISPB2_SER_CLK), "toshiba_backlight_en");
	gpio_direction_output(IOMUX_TO_GPIO(MX51_PIN_DISPB2_SER_CLK), 0);

	/* Camera: power down */
	gpio_request(IOMUX_TO_GPIO(MX51_PIN_CSI1_D8), "camera_powerdown");
	gpio_direction_output(IOMUX_TO_GPIO(MX51_PIN_CSI1_D8), 1);

	/* Camera: reset de-asserted */
	gpio_request(IOMUX_TO_GPIO(MX51_PIN_DISPB2_SER_DIO), "camera_reset");
	gpio_direction_output(IOMUX_TO_GPIO(MX51_PIN_DISPB2_SER_DIO), 1);

	/* Bluetooth: reset de-asserted */
	gpio_request(IOMUX_TO_GPIO(MX51_PIN_GPIO1_9), "bluetooth reset");
	gpio_direction_output(IOMUX_TO_GPIO(MX51_PIN_GPIO1_9), 1);
	/* module on */
	gpio_request(IOMUX_TO_GPIO(MX51_PIN_GPIO1_8), "bluetooth on/off");
	gpio_direction_output(IOMUX_TO_GPIO(MX51_PIN_GPIO1_8), 1);
	/* sleepx as input */
	gpio_request(IOMUX_TO_GPIO(MX51_PIN_GPIO1_6), "bluetooth sleepx");
	gpio_direction_input(IOMUX_TO_GPIO(MX51_PIN_GPIO1_6));
#if 0
	/* GSM/GPRS: power down */
	gpio_request(IOMUX_TO_GPIO(MX51_PIN_EIM_D22), "gsm pwr_on");
	gpio_direction_output(IOMUX_TO_GPIO(MX51_PIN_EIM_D22), 1);
	/* reset asserted */
	gpio_request(IOMUX_TO_GPIO(MX51_PIN_EIM_D23), "gsm reset_n");
	gpio_direction_output(IOMUX_TO_GPIO(MX51_PIN_EIM_D23), 0);
	/* audio lines temporarily as inputs */
	gpio_request(IOMUX_TO_GPIO(MX51_PIN_EIM_D19), "gsm rsck");
	gpio_direction_input(IOMUX_TO_GPIO(MX51_PIN_EIM_D19));
	gpio_request(IOMUX_TO_GPIO(MX51_PIN_EIM_D16), "gsm rfs");
	gpio_direction_input(IOMUX_TO_GPIO(MX51_PIN_EIM_D16));
	gpio_request(IOMUX_TO_GPIO(MX51_PIN_EIM_D21), "gsm rx");
	gpio_direction_input(IOMUX_TO_GPIO(MX51_PIN_EIM_D21));
	gpio_request(IOMUX_TO_GPIO(MX51_PIN_EIM_D20), "gsm tx");
	gpio_direction_input(IOMUX_TO_GPIO(MX51_PIN_EIM_D20));

	/* GPS: extint0 */
	gpio_request(IOMUX_TO_GPIO(MX51_PIN_GPIO1_3), "gps extint0");
	gpio_direction_output(IOMUX_TO_GPIO(MX51_PIN_GPIO1_3), 1);
	/* GPS: timepulse */
	gpio_request(IOMUX_TO_GPIO(MX51_PIN_OWIRE_LINE), "gps timepulse");
	gpio_direction_input(IOMUX_TO_GPIO(MX51_PIN_OWIRE_LINE));
#endif
}

